name: pip_services_metrics
version: "1.0.0"
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This microservice is designed to manage various metrics characterizing the operation of a process.
homepage: https://github.com/pip-services3-dart/pip-services-metrics-dart

environment:
  sdk: ">=2.0.0 <3.0.0"


dev_dependencies:
  test: '>=1.14.2 <2.0.0'